name = "collab-docs"
main = "workers/index.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]
minify = true

# Variáveis de ambiente para OAuth
[vars]
ENVIRONMENT = "development"
FRONTEND_URL = "https://collab-docs-hs8ulhuv7-lucas-antunes-projects.vercel.app"
GITHUB_CLIENT_ID = "Ov23liCo7kBs3oTsBCpo"
GITHUB_CLIENT_SECRET = "9e6b86d3cf48165d77ca9b4641d9ed5ceeac298c"
GOOGLE_CLIENT_ID = "YOUR_GOOGLE_CLIENT_ID"
GOOGLE_CLIENT_SECRET = "YOUR_GOOGLE_CLIENT_SECRET"
JWT_SECRET = "collabdocs-super-secret-jwt-key-2024"

# KV Namespace
[[kv_namespaces]]
binding = "CACHE"
id = "588b9a52eef149828fdab58dfb73d7ff"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "collab-docs-db"
database_id = "5035fcc8-c02e-4290-b880-da14ba523dd9"

# Comentado devido ao plano gratuito
# [[r2_buckets]]
# binding = "STORAGE"
# bucket_name = "collab-docs-storage"

# Comentado devido ao plano gratuito
# [durable_objects]
# bindings = [
#   { name = "DOCUMENT", class_name = "Document" }
# ]

# Comentado devido ao plano gratuito
# [[migrations]]
# tag = "v1"
# new_classes = ["Document"]

# Comentado - não é mais necessário
# [pages]
# pages_build_output_dir = "apps/web/.next"

[[rules]]
type = "ESModule"
globs = ["**/*.js", "**/*.ts"]


