name = "collab-docs"
main = "workers/index.ts"
compatibility_date = "2024-08-20"

[env.production]
vars = { ENVIRONMENT = "production" }

[[d1_databases]]
binding = "DB"
database_name = "COLLAB_DOCS_DB"
database_id = "e0a23c1f-745b-48cd-8269-08aa103a4434"