name = "collab-docs"
main = "workers/index.ts"
compatibility_date = "2024-08-20"

[env.production]
vars = { ENVIRONMENT = "production" }

[[env.production.d1_databases]]
binding = "DB"
database_name = "COLLAB_DOCS_DB"
database_id = "your-database-id"